// Pro Tools-inspired menu definition.
// Each item references an `actions[key]` handler defined in Daw.jsx.

export const PRO_TOOLS_MENUS = {
  File: [
    { id: 'file_new_session', label: 'New Session...', shortcut: 'Ctrl+N', key: 'newSession' },
    { id: 'file_open_session', label: 'Open Session...', shortcut: 'Ctrl+O', key: 'loadSession' },
    { id: 'file_save', label: 'Save', shortcut: 'Ctrl+S', key: 'saveSession' },
    { id: 'file_save_copy_in', label: 'Save Copy In...', key: 'saveCopyIn' },
    { sep: true },
    { id: 'file_import_audio', label: 'Import Audio...', shortcut: 'Ctrl+Shift+I', key: 'importAudio' },
    { id: 'file_import_session_data', label: 'Import Session Data...', key: 'importSessionData' },
    { id: 'file_import_project_json', label: 'Import Project JSON...', key: 'openProject' },
    { sep: true },
    { id: 'file_bounce_mix', label: 'Bounce Mix...', shortcut: 'Ctrl+Alt+B', key: 'bounceMix' },
    { id: 'file_export_stems', label: 'Export Stems (WAV)', key: 'exportStems' },
    { id: 'file_export_json', label: 'Export Session JSON', key: 'exportSession' },
  ],
  Edit: [
    { id: 'edit_undo', label: 'Undo', shortcut: 'Ctrl+Z', key: 'undo' },
    { id: 'edit_redo', label: 'Redo', shortcut: 'Ctrl+Y', key: 'redo' },
    { sep: true },
    { id: 'edit_cut', label: 'Cut', shortcut: 'Ctrl+X', key: 'cutTrack' },
    { id: 'edit_copy', label: 'Copy', shortcut: 'Ctrl+C', key: 'copyTrack' },
    { id: 'edit_paste', label: 'Paste', shortcut: 'Ctrl+V', key: 'pasteTrack' },
    { sep: true },
    { id: 'edit_separate_clip', label: 'Separate Clip at Playhead', shortcut: 'Ctrl+E', key: 'separateClip' },
    { id: 'edit_consolidate', label: 'Consolidate Clip', shortcut: 'Alt+Shift+3', key: 'consolidateClip' },
  ],
  Track: [
    { id: 'track_new_midi', label: 'New MIDI Track', shortcut: 'Ctrl+Shift+N', key: 'addMIDI' },
    { id: 'track_new_audio', label: 'New Audio Track (import)', key: 'addAudio' },
    { id: 'track_group', label: 'Group Tracks...', shortcut: 'Ctrl+G', key: 'groupTracks' },
    { id: 'track_duplicate', label: 'Duplicate Track...', key: 'duplicateTrack' },
    { sep: true },
    { id: 'track_freeze', label: 'Freeze Track', key: 'freezeTrack' },
    { id: 'track_commit', label: 'Commit Track...', shortcut: 'Alt+Shift+C', key: 'commitTrack' },
    { sep: true },
    { id: 'track_delete', label: 'Delete Selected', key: 'deleteSelected' },
  ],
  Event: [
    { id: 'event_dream', label: 'Dream Track (AI)', key: 'openDream' },
    { id: 'event_history', label: 'Dream History', key: 'openHistory' },
    { id: 'event_assistant', label: 'AI Assistant (Chat)', shortcut: 'Ctrl+I', key: 'openAssistant' },
    { id: 'event_magic_gen', label: 'Magic Generator (Suno-style) \u2728', key: 'openMagicGen' },
    { id: 'event_magic_remix', label: 'Magic Re-mix (Demucs \u25b8 Bantu \u25b8 fal.ai) \ud83c\udf9b', key: 'openMagicRemix' },
    { id: 'event_storytelling', label: 'Bantu Storytelling (Mvett \u25b8 Claude) \ud83d\udcd6', key: 'openStorytelling' },
    { sep: true },
    { id: 'event_piano', label: 'Open Piano Roll', key: 'openPiano' },
    { id: 'event_auto_tempo', label: 'Automatic Tempo Detection', key: 'autoTempo' },
    { id: 'event_bantu_grid', label: 'Quantize to Bantu Oral Grid (Innovation RIBA) 🌍', key: 'openBantu' },
  ],
  AudioSuite: [
    { id: 'as_gain', label: 'Gain (Destructive)', key: 'asGain' },
    { id: 'as_eq', label: 'EQ / Filter', key: 'asEq' },
    { id: 'as_reverb', label: 'Reverb Process', key: 'asReverb' },
    { id: 'as_reverse', label: 'Reverse Audio', key: 'asReverse' },
    { sep: true },
    { id: 'as_separate', label: 'Magic12 Source Separation', key: 'magic12Sep' },
    { id: 'as_master', label: 'Magic12 AI Mastering', key: 'magic12Master' },
  ],
  Tools: [
    { id: 'tools_metronome', label: 'Toggle Metronome', shortcut: 'M', key: 'toggleMetronome' },
    { id: 'tools_loop', label: 'Toggle Loop', shortcut: 'L', key: 'toggleLoop' },
    { id: 'tools_record', label: 'Toggle Record', key: 'toggleRecord' },
  ],
  View: [
    { id: 'view_mixer', label: 'Mixer', key: 'openMixer' },
    { id: 'view_theme', label: 'Toggle Theme', key: 'toggleTheme' },
    { sep: true },
    {
      id: 'view_waveforms',
      label: 'Waveforms',
      submenu: [
        { id: 'wf_peak',       label: 'Peak',                 key: 'wfPeak' },
        { id: 'wf_power',      label: 'Power',                key: 'wfPower' },
        { id: 'wf_rectified',  label: 'Rectified',            key: 'wfRectified' },
        { id: 'wf_outlines',   label: 'Outlines',             key: 'wfOutlines' },
        { id: 'wf_crossfades', label: 'Overlapped Crossfades', key: 'wfCrossfades' },
      ],
    },
  ],
  Window: [
    {
      id: 'window_configurations',
      label: 'Configurations',
      submenu: [
        { id: 'win_cfg_list', label: 'Window Configuration List', shortcut: 'Alt+J', key: 'windowConfigList' },
        { id: 'win_cfg_new',  label: 'New Configuration...',       shortcut: 'Alt+Shift+J', key: 'windowConfigNew' },
      ],
    },
    {
      id: 'window_arrange',
      label: 'Arrange',
      submenu: [
        { id: 'arr_tile',         label: 'Tile',            key: 'arrangeTile' },
        { id: 'arr_tile_h',       label: 'Tile Horizontal', key: 'arrangeTileH' },
        { id: 'arr_tile_v',       label: 'Tile Vertical',   key: 'arrangeTileV' },
        { id: 'arr_cascade',      label: 'Cascade',         key: 'arrangeCascade' },
      ],
    },
    { sep: true },
    { id: 'window_disk_usage',   label: 'Disk Usage',    key: 'openDiskUsage' },
    { id: 'window_system_usage', label: 'System Usage',  key: 'openSystemUsage' },
  ],
  Setup: [
    { id: 'setup_playback', label: 'Playback Engine...', key: 'openPlayback' },
    { id: 'setup_io', label: 'I/O Setup...', key: 'openIO' },
    { id: 'setup_preferences', label: 'Preferences...', key: 'openPrefs' },
    { sep: true },
    { id: 'setup_gm', label: 'GM 128 Instruments', key: 'openGM' },
    { id: 'setup_vst', label: 'VST Scan', key: 'openVst' },
    { id: 'setup_plugins', label: 'Plugins List', key: 'openPlugins' },
  ],
  Help: [
    { id: 'help_manual', label: 'User Manual...', shortcut: 'F1', key: 'openManual' },
  ],
};
