"""E2E crash-test of /api/ai/magic-remix with a real synthetic WAV.

Generates a 3 s polyphonic WAV (kick + bass sine + lead arpeggio + noise hat),
posts it to localhost:8001 to bypass the Cloudflare ~100 s timeout, then
asserts the full chain output: 4 Demucs stems + bantu_groove via fal.ai,
plus Bantu grid metadata. Runs ~90-180 s on CPU.

Usage:  python /app/backend/tests/_e2e_magic_remix.py
"""
import io
import math
import struct
import time
import wave

import requests

API = "http://localhost:8001/api/ai"
SR = 44100
DUR = 3.0  # seconds


def synth_polyphonic_wav() -> bytes:
    n = int(SR * DUR)
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        for i in range(n):
            t = i / SR
            # kick at every 0.5s
            beat = (t % 0.5) / 0.5
            kick = 0.6 * math.sin(2 * math.pi * 60 * t) * math.exp(-beat * 25)
            # bass sine
            bass = 0.25 * math.sin(2 * math.pi * 110 * t)
            # lead arpeggio (sawtooth-ish)
            lead_freqs = [440, 523, 659, 783]
            lead = 0.18 * math.sin(2 * math.pi * lead_freqs[int(t * 4) % 4] * t)
            # noise hat at every 0.25s
            hat_beat = (t % 0.25) / 0.25
            hat = 0.12 * ((i * 9301 + 49297) % 233280 / 233280 - 0.5) * math.exp(-hat_beat * 40)
            sample_l = max(-1.0, min(1.0, kick + bass + lead + hat))
            sample_r = max(-1.0, min(1.0, kick * 0.8 + bass + lead * 1.1 + hat))
            w.writeframesraw(struct.pack("<hh", int(sample_l * 30000), int(sample_r * 30000)))
    return buf.getvalue()


def main() -> int:
    # 1) status probe
    r = requests.get(f"{API}/remix-status", timeout=10)
    r.raise_for_status()
    status = r.json()
    print(f"== remix-status ==\n  mode={status['mode']}  fal_ready={status['fal_ready']}  demucs_ready={status['demucs_ready']}")
    assert status["demucs_ready"], "Demucs not ready"

    # 2) generate the WAV
    wav_bytes = synth_polyphonic_wav()
    print(f"== synthetic WAV : {len(wav_bytes)} bytes / {DUR}s stereo 44.1kHz ==")

    # 3) POST to magic-remix with regenerate=true
    print("== POST /api/ai/magic-remix (this takes ~90-180s) ...")
    t0 = time.time()
    r = requests.post(
        f"{API}/magic-remix",
        files={"file": ("crash_test.wav", wav_bytes, "audio/wav")},
        data={
            "bantu_style": "bikutsi_44",
            "density": "16",
            "bars": "4",
            "regenerate": "true" if status["fal_ready"] else "false",
            "regen_prompt": "polyrhythmic mbira and shekere percussion",
            "regen_duration": "8",
        },
        timeout=300,
    )
    elapsed = time.time() - t0
    print(f"== response in {elapsed:.1f}s, status={r.status_code} ==")
    if r.status_code != 200:
        print(f"FAIL body: {r.text[:500]}")
        return 1
    data = r.json()

    # 4) assertions
    print(f"== response id={data['id']}  mode={data['mode']}")
    print(f"   bantu={data['bantu']['style']} density={data['bantu']['density']} bars={data['bantu']['bars']}")
    print(f"   bantu desc: {data['bantu']['description']}")
    print(f"   grid timestamps (first 4 beats): {data['bantu']['time_stamps_beats'][:4]}")

    stems = data.get("stems", {})
    print(f"== stems found: {list(stems.keys())} ==")
    expected = {"vocals", "drums", "bass", "other"}
    missing = expected - set(stems.keys())
    assert not missing, f"missing demucs stems: {missing}"

    total_bytes = 0
    for name, s in stems.items():
        assert s.get("wav_base64"), f"{name}: no base64"
        assert s.get("bytes", 0) > 0, f"{name}: 0 bytes"
        total_bytes += s["bytes"]
        print(f"   {name:14s}  {s['bytes']:>9} bytes")

    if status["fal_ready"]:
        if "bantu_groove" in stems:
            print(f"   ✓ bantu_groove generated by fal.ai ({stems['bantu_groove']['model']})")
            assert stems["bantu_groove"]["bytes"] > 1000, "bantu_groove too small"
        else:
            print("   ⚠ fal.ai bantu_groove SKIPPED (degraded mode)")
    print(f"== TOTAL payload: {total_bytes/1024:.1f} KB ==")
    print(f"== ✓ E2E PASS in {elapsed:.1f}s ==")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
